-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
--
-- Add any additional autocmds here
-- with `vim.api.nvim_create_autocmd`
--
-- Or remove existing autocmds by their group name (which is prefixed with `lazyvim_` for the defaults)
-- e.g. vim.api.nvim_del_augroup_by_name("lazyvim_wrap_spell")

-- Disable cssls diagnostics for waybar/GTK CSS files
-- (@define-color and @color-name are valid GTK CSS but unknown to cssls)
-- vim.api.nvim_create_autocmd("LspAttach", {
--   pattern = { "*/waybar/*.css", "*/hypr/*.css" },
--   callback = function(args)
--     local client = vim.lsp.get_client_by_id(args.data.client_id)
--     if client and client.name == "cssls" then
--       vim.lsp.buf_detach_client(args.buf, args.data.client_id)
--     end
--   end,
--   desc = "Detach cssls from GTK CSS files (GTK @define-color is not standard CSS)",
-- })
