-- ~/.config/hypr/hyprland.lua
-- Hyprland 0.55+ Lua configuration
-- Reference: https://wiki.hypr.land/Configuring/Start/
-- Remove autogenerated = true once you have customized this file

--------------------
---- VARIABLES -----
--------------------

local terminal = "kitty"
local fileManager = "thunar"
local browser = "brave"
local mainMod = "SUPER"

--------------------
---- MONITORS ------
--------------------

hl.monitor({
  output   = "",
  mode     = "preferred",
  position = "auto",
  scale    = "1",
})

-- Optional: mirror HDMI to internal display
-- hl.monitor({ output = "HDMI-A-1", mode = "1882x1080@60",
--              position = "auto", scale = 1, mirror = "eDP-1" })

--------------------
---- AUTOSTART -----
--------------------

-- hl.exec_cmd() is async — no & needed
-- hl.on("hyprland.start") fires once at boot, not on config reload
hl.on("hyprland.start", function()
  hl.exec_cmd("gnome-keyring-daemon --start --components=secrets")
  hl.exec_cmd("waybar")
  hl.exec_cmd("swaync")
  hl.exec_cmd("clipse -listen")
  hl.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/wallpaper-init.sh")
end)

--------------------
-- ENVIRONMENT -----
--------------------

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("LIBVA_DRIVER_NAME", "iHD")
hl.env("WLR_NO_HARDWARE_CURSORS", "0")

--------------------
---- LOOK & FEEL ---
--------------------

hl.config({
  general = {
    gaps_in          = 5,
    gaps_out         = 14,
    border_size      = 2,
    -- Fallback colors — overridden by matugen's apply-colors.sh
    -- after the first wallpaper pick via hyprctl keyword
    col              = {
      active_border   = "rgba(7986CBee) rgba(4DB6ACee) 45deg",
      inactive_border = "rgba(37474Faa)",
    },
    resize_on_border = true,
    allow_tearing    = false,
    layout           = "dwindle",
  },
})

hl.config({
  decoration = {
    rounding         = 12,
    rounding_power   = 2,
    active_opacity   = 1.0,
    inactive_opacity = 0.93,
    shadow           = {
      enabled      = true,
      range        = 18,
      render_power = 3,
      color        = "rgba(00000060)",
      offset       = "0 4",
    },
    blur             = {
      enabled           = true,
      size              = 6,
      passes            = 3,
      vibrancy          = 0.18,
      vibrancy_darkness = 0.5,
      new_optimizations = true,
      xray              = false,
    },
  },
})

--------------------
---- ANIMATIONS ----
--------------------

hl.curve("easeOutExpo", { type = "bezier", points = { { 0.16, 1 }, { 0.3, 1 } } })
hl.curve("easeOutBack", { type = "bezier", points = { { 0.34, 1.56 }, { 0.64, 1 } } })
hl.curve("easeInOutSine", { type = "bezier", points = { { 0.37, 0 }, { 0.63, 1 } } })
hl.curve("linear", { type = "bezier", points = { { 0, 0 }, { 1, 1 } } })

hl.animation({ leaf = "windows", enabled = true, speed = 4, bezier = "easeOutBack" })
hl.animation({ leaf = "windowsIn", enabled = true, speed = 4, bezier = "easeOutBack", style = "popin 75%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 2, bezier = "easeInOutSine", style = "popin 80%" })
hl.animation({ leaf = "fadeIn", enabled = true, speed = 3, bezier = "easeOutExpo" })
hl.animation({ leaf = "fadeOut", enabled = true, speed = 2, bezier = "easeInOutSine" })
hl.animation({ leaf = "border", enabled = true, speed = 8, bezier = "easeOutExpo" })
hl.animation({ leaf = "borderangle", enabled = true, speed = 80, bezier = "linear", style = "loop" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 4, bezier = "easeOutExpo", style = "slidefade 20%" })

--------------------
---- LAYOUTS -------
--------------------

hl.config({
  dwindle = {
    pseudotile     = true,
    preserve_split = true,
    smart_split    = true,
  },
  master = {
    new_status = "master",
  },
  misc = {
    force_default_wallpaper      = 0,
    disable_hyprland_logo        = true,
    animate_manual_resizes       = true,
    animate_mouse_windowdragging = true,
    vfr                          = true,
  },
})

--------------------
---- INPUT ---------
--------------------

hl.config({
  input = {
    kb_layout    = "us",
    follow_mouse = 1,
    sensitivity  = 0.3,
    touchpad     = {
      natural_scroll       = true,
      tap_to_click         = true,
      drag_lock            = true,
      disable_while_typing = true,
    },
  },
  gestures = {
    workspace_swipe                    = true,
    workspace_swipe_distance           = 250,
    workspace_swipe_invert             = true,
    workspace_swipe_min_speed_to_force = 15,
    workspace_swipe_cancel_ratio       = 0.15,
    workspace_swipe_create_new         = true,
  },
  xwayland = {
    force_zero_scaling = true,
  },
})

-- ThinkPad TrackPoint (red dot)
hl.config({
  device = {
    name        = "tpps/2-elan-trackpoint",
    sensitivity = -0.5,
  },
})

--------------------
---- KEYBINDINGS ---
--------------------

-- Core apps
hl.bind(mainMod .. " + RETURN", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd(browser))
hl.bind(mainMod .. " + W", hl.dsp.window.kill())
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
hl.bind(mainMod .. " + J", hl.dsp.layout("togglesplit"))
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen({ internal = 0 }))
hl.bind(mainMod .. " SHIFT + F", hl.dsp.window.fullscreen({ internal = 1 }))

-- App launcher
hl.bind(mainMod .. " + M",
  hl.dsp.exec_cmd("rofi -show drun -theme ~/.config/rofi/appmenu.rasi"))

-- Emoji picker
hl.bind(mainMod .. " + period",
  hl.dsp.exec_cmd("rofimoji"))
hl.bind(mainMod .. " SHIFT + period",
  hl.dsp.exec_cmd("rofimoji --files ~/.config/rofimoji/material_design.csv"))
hl.bind(mainMod .. " CTRL + period",
  hl.dsp.exec_cmd("rofimoji --files ~/.config/rofimoji/cozette.csv"))

-- Wallpaper picker (awww + matugen)
hl.bind(mainMod .. " + K", hl.dsp.exec_cmd("~/.config/rofi/wallpaper.sh"))

-- Clipboard
hl.bind(mainMod .. " + C", hl.dsp.exec_cmd("kitty --class clipse -e clipse"))

-- Power menu
hl.bind(mainMod .. " + Escape", hl.dsp.exec_cmd("~/.config/rofi/powermenu.sh"))

-- Screenshots — grim + slurp + satty
hl.bind("Print",
  hl.dsp.exec_cmd('grim -g "$(slurp)" - | satty --filename -'))
hl.bind(mainMod .. " + Print",
  hl.dsp.exec_cmd("grim - | satty --filename -"))
hl.bind(mainMod .. " CTRL + Print",
  hl.dsp.exec_cmd(
    'grim -g "$(slurp)" ~/Pictures/screenshots/$(date +%Y%m%d_%H%M%S).png && notify-send "Screenshot saved"'))

-- Reload waybar
hl.bind(mainMod .. " + L", hl.dsp.exec_cmd("pkill waybar && waybar &"))

-- Exit Hyprland
hl.bind(mainMod .. " + R", hl.dsp.exit())

-- Focus movement
hl.bind(mainMod .. " + left", hl.dsp.window.focus("l"))
hl.bind(mainMod .. " + right", hl.dsp.window.focus("r"))
hl.bind(mainMod .. " + up", hl.dsp.window.focus("u"))
hl.bind(mainMod .. " + down", hl.dsp.window.focus("d"))

-- Move windows
hl.bind(mainMod .. " SHIFT + left", hl.dsp.window.move("l"))
hl.bind(mainMod .. " SHIFT + right", hl.dsp.window.move("r"))
hl.bind(mainMod .. " SHIFT + up", hl.dsp.window.move("u"))
hl.bind(mainMod .. " SHIFT + down", hl.dsp.window.move("d"))

-- Resize windows
hl.bind(mainMod .. " CTRL + left",
  hl.dsp.window.resize({ x = -40, y = 0, relative = true }), { repeating = true })
hl.bind(mainMod .. " CTRL + right",
  hl.dsp.window.resize({ x = 40, y = 0, relative = true }), { repeating = true })
hl.bind(mainMod .. " CTRL + up",
  hl.dsp.window.resize({ x = 0, y = -40, relative = true }), { repeating = true })
hl.bind(mainMod .. " CTRL + down",
  hl.dsp.window.resize({ x = 0, y = 40, relative = true }), { repeating = true })

-- Workspaces 1–9 and 0 (workspace 10)
for i = 1, 9 do
  hl.bind(mainMod .. " + " .. i, hl.dsp.workspace(i))
  hl.bind(mainMod .. " SHIFT + " .. i, hl.dsp.window.move({ workspace = i }))
end
hl.bind(mainMod .. " + 0", hl.dsp.workspace(10))
hl.bind(mainMod .. " SHIFT + 0", hl.dsp.window.move({ workspace = 10 }))

-- Scratchpad
hl.bind(mainMod .. " + S", hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll workspaces with mouse wheel
hl.bind(mainMod .. " + mouse_down", hl.dsp.workspace("e+1"))
hl.bind(mainMod .. " + mouse_up", hl.dsp.workspace("e-1"))

-- Move/resize windows with mouse
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.move_window(), { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize_window(), { mouse = true })

-- Volume (wpctl — PipeWire)
hl.bind("XF86AudioRaiseVolume",
  hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume",
  hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true, repeating = true })
hl.bind("XF86AudioMute",
  hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true })
hl.bind("XF86AudioMicMute",
  hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true })

-- Brightness (ThinkPad Fn keys)
hl.bind("XF86MonBrightnessUp",
  hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown",
  hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"), { locked = true, repeating = true })

-- Media keys
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

--------------------
---- WINDOW RULES --
--------------------

-- Float common utility apps
hl.window_rule({
  match  = { class = "^(org.pulseaudio.pavucontrol|clipse|blueman-manager|tlpui|nm-connection-editor|lxappearance|qt5ct|nwg-look)$" },
  float  = true,
  size   = { 800, 652 },
  center = true,
})

-- Float file picker dialogs
hl.window_rule({
  match  = { title = "^(Open|Save|Save As|File Chooser).*$" },
  float  = true,
  center = true,
})

-- Picture-in-picture — bottom-right corner
hl.window_rule({
  match = { title = "^(Picture in picture)$" },
  float = true,
  size  = { 480, 270 },
  move  = { "100%-490", "100%-280" },
})

-- Kitty — active 0.95 / inactive 0.88 opacity
hl.window_rule({
  match   = { class = "^(kitty)$" },
  opacity = "0.95 0.88",
})
